### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by AdrianoCahete** [ch99q/nuxt-pdf#8]
Hey Christian, it's me again :D 

I updated to use the latest version and update the configs like what you say on #7 .

After that, when I try to run "npm run generate", the follow  error appears:
```
ℹ Generating pdfs                                                                                      17:50:51

 FATAL  The "path" argument must be of type string. Received undefined                                 17:50:52

  at validateString (internal/validators.js:120:11)
  at Proxy.resolve (path.js:139:9)
  at node_modules\nuxt-pdf\lib\module.js:130:18
  at async Nuxt.callHook (node_modules\hable\dist\hable.js:1:1021)
  at async Generator.generate (node_modules\@nuxt\generator\dist\generator.js:126:5)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-generate.js:362:24)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:2798:7)


   ╭────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                            │
   │   ✖ Nuxt Fatal Error                                                                       │
   │                                                                                            │
   │   TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received   │
   │   undefined                                                                                │
   │                                                                                            │
   ╰────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adrianocahete.dev@2.2.0 generate: `nuxt generate --modern`
```

My current config for pdf is that:
```
pdf: {
    // Output folder for generated pdf.
    dir: 'static',

    // Function options for page.pdf([options])
    // Read more: https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pagepdfoptions
    pdf: {
      format: 'A4',
      printBackground: true
    },

    // PDF Meta configuration
    meta: {
      title: process.env.npm_package_description,

      author: process.env.npm_package_author,
      subject: process.env.npm_package_description + ' @ ' + process.env.url,

      producer: process.env.npm_package_author,

      creationDate: new Date(),

      keywords: ['pdf', 'resume', process.env.npm_package_author]
    },

    // PDF generation routes. (expanding nuxt.generate)
    routes: [
      {
        file: 'resume-artifacts/Adriano_Cahete-Resume.pdf',
        route: 'resume',

        meta: {
          title: process.env.npm_package_description
        }
      }
    ]
  },
```

`resume` route/page exists (can be viewed on browsers), `resume-artifacts` too, other resumes are in there.

`dev task` works, but don't generate the resume in the folder. If I remove pdf configs build works, but nothing is generated (as expected, I think).

I'm doing something wrong here?

**Comment by ch99q** [comment]
@AdrianoCahete What version of the module are you running, can't find anything in the module.js pointing to your problem :/

Maybe try `npm install nuxt-pdf@1.1.1 --save-dev` and try again, if it still doesn't work I will try to take a deeper look into the problem.
